ACCESS_TOKEN = '1564171796517093378-Pn2Q63dWACFL0gFqJbRlJ1r9F0tLX5'
ACCES_TOKEN_SECRET = '3SC5lhZk94JMQb56QYDtzJLeMCcyQnJfKgXrpFAnz0M3l'

# private local host environment
# public APIs
# crowd_prod
API_KEY = 'bI2jKmgOqYK9yaiA5ZkTcAExq'
API_KEY_SECRET = 'CeBjN7hDmjVC6Jdpfl5Sjwzs3faknTsUbRWxvRDsXNMZKzvytT'
BEARER_TOKEN = 'AAAAAAAAAAAAAAAAAAAAAAoJggEAAAAAzsozd047CjW5Mn7IUOxF3qFm%2F84%3DCYlhL2JNRUIu9LTnWd40Y2SYyMtZ7VVPatmoHhFNav29oJj0bk'
# crowd_test
API_KEY = 'UVCpm1lEVdRPVCyN84h05LuNn'
API_KEY_SECRET = 'nKKz6q4h2OfaUr1H5Em7E233eJPzTKXGrt6dd4n0GVuw8JnFGv'
BEARER_TOKEN = 'AAAAAAAAAAAAAAAAAAAAAPkIggEAAAAA21ZQqO3xoQ4C%2BP6rE%2B5JG1SLjfA%3DwdZCB75sYiPvLMwOsey9LKVyilhh7rRXfqkkfXAS84U5SxHcZB'
# crowd_feel
API_KEY = '1MwQ1Q26j5At31dZqhIXadMWZ'
API_KEY_SECRET = 'uRVvWVyITAsl7r0rklvuIpWG4dtE96idgbX4vJB93ey3VM2RwS'
BEARER_TOKEN = 'AAAAAAAAAAAAAAAAAAAAAOf3gQEAAAAAQf43%2F%2FwyhFsWbvTngSS7V3pORxc%3Dwam9DxniYYZf5XOF6MyEMfkPEvsvXktzUdeWsBPhtjVLJeWp5m'

# https://developer.twitter.com/en/docs/authentication/guides/v2-authentication-mapping